theme: minima
show_excerpts: true
title: MountainRoost
description: A personal blog about things from rock climbing to home automation.
author: John Orndorff
email: "johnornd@gmail.com"
include: [".well-known"]
